### ISSUE TITLE
Add multi-arch support

### ISSUE THREAD

**Issue by ben-fussell** [cybcon/modbus-client#9]
@cybcon - first, thank you for publishing your modbus tools! 

It would be super helpful to be able to run the `modbus-client` docker image on an arm device, so would it be possible to update the build-and-push action steps to something like this?

```
    steps:
      - name: Checkout GIT repository
        uses: actions/checkout@v3
      - name: Get the application version
        id: application-version
        run: |
          image_version=$(grep "^LABEL site.local.program.version=" Dockerfile | cut -d= -f2 | sed -e 's/"//g')
          if [ -z "${image_version}" ]; then
            echo "ERROR: unable to detect version number!" >&2
            exit 1
          fi
          echo "tag=${image_version}" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          platforms: linux/amd64, linux/arm64
          tags: oitc/modbus-client:${{steps.application-version.outputs.tag}}
```
